# Generated by Django 4.2.7 on 2023-12-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_data",
            field=models.DateField(),
        ),
    ]
